import type { Metadata } from 'next'
import { Playfair_Display, Montserrat, Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Layout/Navbar'
import Footer from '@/components/Layout/Footer'
import { cn } from '@/lib/utils'
import ReservationModal from '@/components/ReservationModal'
import SideCart from '@/components/SideCart'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        playfair.variable,
        montserrat.variable,
        'font-sans',
        inter.variable,
      )}
    >
      <body className='min-h-full flex flex-col'>
        <Navbar />

        <Suspense fallback={null}>{children}</Suspense>
        <Footer />
        <Suspense fallback={null}>
          <ReservationModal />
        </Suspense>
        <SideCart />
      </body>
    </html>
  )
}
