import type { Metadata } from 'next'
import { Playfair_Display, Montserrat, Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

import { Suspense } from 'react'
import { Toaster } from 'sonner'

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-sans',
})

const playfair = Playfair_Display({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-playfair',
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-montserrat',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        playfair.variable,
        montserrat.variable,
        'font-sans',
        inter.variable,
      )}
    >
      <body className='min-h-full flex flex-col'>
        <Suspense fallback={null}>{children}</Suspense>
        <Toaster />
      </body>
    </html>
  )
}
