import { customAlphabet } from 'nanoid'
import { prisma } from '@/lib/prisma'

const alphabet = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'

const generateCode = customAlphabet(alphabet, 6)

export async function generateUniqueOrderNumber(
  prefix = 'LM',
): Promise<string> {
  let isUnique = false
  let orderNumber = ''

  while (!isUnique) {
    orderNumber = `${prefix}-${generateCode()}` // Generated by: "LM-8K3P"

    // We ensure 100% uniqueness by checking in the database
    const existing = await prisma.order.findUnique({
      where: { orderNumber },
      select: { id: true },
    })

    if (!existing) {
      isUnique = true
    }
  }

  return orderNumber
}
