import type { Metadata } from 'next'
import Navbar from '@/components/Layout/Navbar'
import Footer from '@/components/Layout/Footer'
import ReservationModal from '@/components/ReservationModal'
import SideCart from '@/components/SideCart'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />

      <ReservationModal />
      <SideCart />
    </>
  )
}
